---
- name: Install Apache httpd
  hosts: all
  user: ansible
  connection: ssh
  gather_facts: no
  become: yes
  tasks:
    - name: Install Apache Web Server
      yum: name=httpd state=installed
      notify: restart_httpd
    - name: Enable httpd
      service:
        name: httpd
        enabled: yes
  handlers:
    - name: restart_httpd
      service: 
        name: httpd 
        state: restarted