---
- name: Install Apache httpd
  hosts: all
  user: ansible
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      notify: restart_httpd
  handlers:
    - name: restart_httpd
      action: service name=httpd state=restarted