---
- name: Distribute SSH Public Key
  hosts: all
  gather_facts: false
  become: true
  connection: ssh
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/root/.ssh/ansible-key.pub') }}"